-- GFSO — machine-checked formalization of the canon's formal spine (docs/applied_gfso_v4_en.md).
--
-- THE NAMED TIERS (the canon's own numbering, §1.4 — a derivation stack, NOT a claim that tier N+1
-- is generated by tier N: the canon calls that table "direction-neutral", and tier 7, the theory
-- model, GROUNDS the apparatus rather than being produced by it):
--   Tier 0  AXIOMS        A1, A2                                  (definitional — see Postulates)
--   Tier 1  PRIMITIVES    T, D, Dep, Del (V derived)              Ontology
--   Tier 2  VALIDATION    L, ⊗, T1                                Binarity · AndUniqueness · Compositionality
--   Tier 3  FAILURE MODES FM-1..7                                 FailureModes
--     3b    TIME          the operational axis (derived; CA2 discharged)   Time
--   Tier 4  STANDARDS     STD-1..4, the nine CHECKs (1, 1b, 2–8), Syntactic/Semantic/Pragmatic      Standards
--   Tier 5  PROTOCOL      Signals (12), States (12), Inv-1..7     Protocol · Fsm
--   Tier 6  MEASUREMENT   Q (5), T10, T11                         Metrics
--   Tier 7  THEORY MODEL  S/Ŝ, Contact, Lemma 1, d1–d6            TheoryModel
--     7b    LINKS         the five constitutive links             Links
--
-- CLOSURE: `Postulates` lists every irreducible postulate of GFSO and how it is carried
-- (Lean axiom / definitional / hypothesis-form). `check_axioms.lean` verifies nothing else hides.
import GFSO.Ontology
import GFSO.Compositionality
import GFSO.Binarity
import GFSO.AndUniqueness
import GFSO.FailureModes
import GFSO.Time
import GFSO.Standards
import GFSO.Fsm
import GFSO.FsmCanon
import GFSO.Protocol
import GFSO.Metrics
import GFSO.Grading
import GFSO.TheoryModel
import GFSO.Links
import GFSO.Postulates
