-- GFSO — machine-checked formalization of the canon's formal spine (docs/applied_gfso_v3.md).
--
-- THE NAMED TIERS (read top-down; each tier is GENERATED by the one above it):
--   Tier 0  AXIOMS        A1, A2                                  (definitional — see Postulates)
--   Tier 1  PRIMITIVES    T, D, Dep, Del (V derived)              Ontology
--   Tier 2  VALIDATION    L, ⊗, T1                                Binarity · AndUniqueness · Compositionality
--   Tier 3  FAILURE MODES FM-1..7                                 FailureModes
--     3b    TIME          the operational axis (Axiom 2)          Time
--   Tier 4  STANDARDS     STD-1..4, CHECK-1..8, Levels 0/1/2      Standards
--   Tier 5  PROTOCOL      Signals (12), States (12), Инв-1..7     Protocol · Fsm
--   Tier 6  MEASUREMENT   Q (5), T10, T11                         Metrics
--   Tier 7  THEORY MODEL  S/Ŝ, contact, Lemma 1, D1–D6            TheoryModel
--     7b    LINKS         the five constitutive links             Links
--
-- CLOSURE: `Postulates` lists every irreducible postulate of GFSO and how it is carried
-- (Lean axiom / definitional / hypothesis-form). `check_axioms.lean` verifies nothing else hides.
import GFSO.Ontology
import GFSO.Compositionality
import GFSO.Binarity
import GFSO.AndUniqueness
import GFSO.FailureModes
import GFSO.Time
import GFSO.Standards
import GFSO.Fsm
import GFSO.Protocol
import GFSO.Metrics
import GFSO.TheoryModel
import GFSO.Links
import GFSO.Postulates
